lang: en
project:
  type: book
  output-dir: docs
  resources: resources
execute:
  freeze: auto
book:
  title: 5023B
  subtitle: ''
  author: Philip Leftwich
  doi: ''
  license: CC-BY
  description: Statistical skills for Biologists
  cover-image: images/logos/logo.png
  image: images/logos/logo.png
  favicon: images/logos/logo.png
  cookie-consent: false
  google-analytics: ''
  page-navigation: true
  search: true
  sidebar:
    title: ''
    logo: ''
    search: true
    contents: ''
    style: floating
    background: light
    foreground: dark
    border: true
    alignment: left
    collapse-level: 1
    pinned: true
    header: ''
    footer: ''
  margin-header: ''
  page-footer: CC-BY (2024) Philip Leftwich
  chapters:
  - index.qmd
  - part: "Day 1"
    chapters:
    - 01-projects.qmd
    - 02-tidyverse.qmd
    - 03-functions.qmd
    - 04-iteration.qmd
    - 05-tidy-evaluation.qmd
  - part: "Day 2"
    chapters:
    - 06-reproducibility.qmd
    - 07-code-review.qmd
  - part: "Day 3: Data Visualisation"
    chapters:
    - 08-ggplot.qmd
  - part: "Day 3: Quarto"
    chapters:
    - 09-quarto-workshop-revised.qmd
  - part: "Day 3: Github"
    chapters:
    - 10-github.qmd
    - 10a-github-automation-tutorial.qmd
  - part: "Day 4"
    chapters:
    - 11-AI-programming-integrated.qmd

bibliography:
  - include/packages.bib
  - include/references.bib
csl: include/apa.csl
format:
  html:
    theme:
      light:
      - flatly
      - include/light.scss
      dark:
      - darkly
      - include/dark.scss
    css:
    - https://use.fontawesome.com/releases/v5.13.0/css/all.css
    - include/booktem.css
    - include/webex.css
    - include/glossary.css
    - include/style.css
    df-print: kable
    code-link: true
    code-fold: false
    code-line-numbers: true
    code-overflow: scroll
    code-copy: hover
    highlight-style: a11y
    mainfont: ''
    monofont: ''
    include-after-body:
    - include/webex.js
    - include/script.js
