lang: en
project:
  type: book
  output-dir: docs
  resources: resources
execute:
  freeze: auto
book:
  title: Advancing in R
  subtitle: ''
  author: Philip Leftwich & Ed Ivimey-Cook
  doi: ''
  license: CC-BY
  cover-image: images/logos/logo.jpg
  image: images/logos/logo.jpg
  favicon: images/logos/logo.jpg
  cookie-consent: false
  google-analytics: ''
  page-navigation: true
  search: true
  sidebar:
    title: ''
    logo: ''
    search: true
    contents: ''
    style: floating
    background: light
    foreground: dark
    border: true
    alignment: left
    collapse-level: 1
    pinned: true
    header: ''
    footer: ''
  margin-header: ''
  page-footer: CC-BY (2026) Philip Leftwich & Ed Ivimey-Cook
  chapters:
  - index.qmd
  - part: "Day 1: Advancing in R"
    chapters:
    - 01-projects.qmd
    - 02-tidyverse.qmd
    - 03-functions.qmd
    - 04-iteration.qmd
    - 05-tidy-evaluation.qmd
  - part: "Day 2: Reproducibility"
    chapters:
    - 06-reproducibility.qmd
    - 07-code-review.qmd
  - part: "Day 3: Data Visualisation"
    chapters:
    - 08-ggplot.qmd
    - 08b-ggplot.qmd
    - 08c-ggplot.qmd
    - 08d-ggplot.qmd
    - 08e-ggplot.qmd
    
  - part: "Day 3: Quarto"
    chapters:
    - 09-quarto-workshop-revised.qmd
  - part: "Day 3: Github"
    chapters:
    - 10-github.qmd
    - 10a-github-automation-tutorial.qmd
  - part: "Day 4: AI-assisted programming"
    chapters:
    - 11-AI-programming-integrated.qmd
    - 11b-AI-programming-integrated.qmd
    - 11c-AI-programming-integrated.qmd
    - 11d-AI-programming-integrated.qmd
    - 11e-AI-programming-integrated.qmd
    - 11f-AI-programming-integrated.qmd
    - 11g-AI-programming-integrated.qmd
    - 11h-AI-programming-integrated.qmd
  appendices:
  - r-basics.qmd
  - tidy-data.qmd
  - join.qmd
  - 12-gt.qmd
  - 12a-ggplot.qmd
  - 12b-ggplot2.qmd
  - working_with_large_data.qmd
  - references.qmd
bibliography:
  - include/packages.bib
  - include/references.bib
csl: include/apa.csl
format:
  html:
    theme:
      light:
      - flatly
      - include/light.scss
      dark:
      - darkly
      - include/dark.scss
    css:
    - https://use.fontawesome.com/releases/v5.13.0/css/all.css
    - include/booktem.css
    - include/webex.css
    - include/glossary.css
    - include/style.css
    df-print: kable
    code-link: true
    code-fold: false
    code-line-numbers: true
    code-overflow: scroll
    code-copy: hover
    highlight-style: a11y
    mainfont: ''
    monofont: ''
    include-after-body:
    - include/webex.js
    - include/script.js
