# Overview {.unnumbered}

This course is designed for anyone with basic knowledge of R who is looking to enhance their skills and take their programming abilities to the next level. Each session in the course will be hands-on, providing you with practical examples to work through and apply the concepts you've learned, and lots of support to answer questions and overcome any challenges.

## Learning outcomes

1. A grounding in R
2. Project based workflows
3. Tidyverse for data wrangling
4. Writing functions and running iterations
5. Advanced tidyverse tricks
6. GGplot for data visuals
7. Making tables with gt
8. Making reports with Quarto
9. Using Github


## How to use this book
For many of the chapters, we will provide the code you need to use. You can copy and paste from the book using the clipboard in the top-right corner.

We also provide the solutions to many of the activities. No-one is going to check whether you tried to figure it out yourself rather than going straight to the solution but remember this: if you copy and paste without thinking, you will learn nothing.

Finally, on occasion we will make updates to the book such as fixing typos and including additional detail or activities and as such this book should be considered a living document. Please tell me if you find any mistakes.


## Packages

```
## Core Packages:
- tidyverse
- palmerpenguins
- here
- janitor
- fs

## Data Wrangling & Import:
- data.table
- dtplyr
- dbplyr
- arrow
- duckdb
- rvest
- assertr
- tidylog

## Data Exploration:
- skimr
- naniar

## Statistical Modelling:
- broom
- broom.mixed
- lme4
- lmerTest
- emmeans
- glmnet
- caret
- randomForest
- rpart
- xgboost

## Testing & Benchmarking:
- testthat
- bench

## Working with Tables:
- gt
- gtExtras
- kableExtra

## ggplot Extensions:
- patchwork
- scales
- colorBlindness
- colorspace
- ggdist
- ggrepel
- ggtext
- ggview
- ggbeeswarm
- gghighlight
- ggh4x
- ggpubr
- ggdensity
- ggbump
- ggalt
- ggridges
- ggforce
- geomtextpath
- ragg
- png
- showtext
- RColorBrewer
- gapminder

## Maps & Spatial:
- sf
- rnaturalearth

## Reproducible Reports:
- knitr
- quarto

## Interactive & Visualisation:
- plotly
- shiny

## Working with Github:
- gitcreds
- usethis
- renv

## AI & Other Tools:
- tidychatmodels
- webexercises
- downloadthis
- waldo

```

## Other software

- R version 4.0.0 or later
- RStudio
- Rtools (compatible with your computer)
- Git (compatible with your computer)


```{r cite-packages, include = FALSE}
# automatically create a bib database for R packages
# add any packages you want to cite here
knitr::write_bib(c(
  .packages(), 'rstatix', 'patchwork', 'here', 'kableExtra', 'plotly', 'gitcreds', 'usethis', 'ggridges', 'scales', 'purrr', 'tinytex', 'gt', 'broom', 'tidyverse', 'rstatix', 'performance', 'see', 'lme4', 'lmerTest', 'DHARMa', 'glmmTMB', 'nlme', 'ggeffects', 'sjPlot', 'DHARMa', 'report', 'MuMIn', 'palmerpenguins', 'colorBlindness', 'skimr', 'ggplot2', 'sandwich', 'parameters', 'lubridate', 'forcats', 'rvest', 'naniar', 'mice', 'profvis', 'memoise', 'digest', 'sqldf', 'dbplyr', 'doParallel', 'foreach', 'furrr', 'devtools', 'tidychatmodels'
), 'include/packages.bib')


# Set ggplot theme for book
library(ggplot2)


my_theme <- theme_minimal(base_size = 16) + 
  theme(
    panel.grid = element_blank(),  # Removes gridlines
    axis.line = element_line(color = "black")  # Adds x and y axis lines
  )

theme_set(my_theme)

```
