<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Block 1: Reproducibility – Advancing in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-code-review.html" rel="next">
<link href="./05-tidy-evaluation.html" rel="prev">
<link href="./images/logos/logo.jpg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-b754b9fd3853d7e56faef54c29c5d52b.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-de8274a4d1ecc1e6aaeaf6e5564b5074.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-b754b9fd3853d7e56faef54c29c5d52b.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e0a43ceb7c9e63dd117097429fd00833.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-d7d11905500e7839d0ae783f44cd34c1.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-e0a43ceb7c9e63dd117097429fd00833.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="include/booktem.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/glossary.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-reproducibility.html">Day 2: Reproducibility</a></li><li class="breadcrumb-item"><a href="./06-reproducibility.html">Block 1: Reproducibility</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Advancing in R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Day 1: Advancing in R</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-projects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 1: Project-based workflows</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 2: Getting more out of tidyverse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 3: Writing functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-iteration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 4: Iterations with purrr</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-tidy-evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 5: Tidy evaluation and data masking</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Day 2: Reproducibility</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-reproducibility.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Block 1: Reproducibility</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-code-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 2: Code Review</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Day 3: Data Visualisation</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 1: Foundations and graph crimes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08b-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 2: Choosing the right figure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08c-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 3: Themes and scales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08d-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 4: Extensions in action</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08e-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 5: Saving figures correctly</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Day 3: Quarto</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-quarto-workshop-revised.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Day 3: Github</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-github.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 1: Github</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10a-github-automation-tutorial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 2: Github Automations</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Day 4</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-AI-programming-integrated.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 1: AI-Assisted R Programming</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11b-AI-programming-integrated.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 2: AI - Inline completions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11c-AI-programming-integrated.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 3: Debugging with AI</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11d-AI-programming-integrated.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 4: Github Copilot Chat in Ask mode</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">R Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidy-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tidy data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-gt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Making tables with gt</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12a-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">ggplot</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12b-ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">ggplot2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#repro-what" id="toc-repro-what" class="nav-link active" data-scroll-target="#repro-what">Part 1 — What is reproducibility?</a>
  <ul class="collapse">
<li><a href="#analytical-and-computational-reproducibility" id="toc-analytical-and-computational-reproducibility" class="nav-link" data-scroll-target="#analytical-and-computational-reproducibility">Analytical and computational reproducibility</a></li>
  <li><a href="#the-replication-crisis-starts-with-reproducibility" id="toc-the-replication-crisis-starts-with-reproducibility" class="nav-link" data-scroll-target="#the-replication-crisis-starts-with-reproducibility">The replication crisis starts with reproducibility</a></li>
  </ul>
</li>
  <li>
<a href="#repro-multiverse" id="toc-repro-multiverse" class="nav-link" data-scroll-target="#repro-multiverse">Part 2 — Many analysts, many answers</a>
  <ul class="collapse">
<li><a href="#background-the-garden-of-forking-paths" id="toc-background-the-garden-of-forking-paths" class="nav-link" data-scroll-target="#background-the-garden-of-forking-paths">Background: the garden of forking paths</a></li>
  <li><a href="#you-are-the-analyst" id="toc-you-are-the-analyst" class="nav-link" data-scroll-target="#you-are-the-analyst">You are the analyst</a></li>
  <li><a href="#reporting-on-the-same-scale-emmeans" id="toc-reporting-on-the-same-scale-emmeans" class="nav-link" data-scroll-target="#reporting-on-the-same-scale-emmeans">Reporting on the same scale: emmeans</a></li>
  <li><a href="#the-results---temporary-graph-to-be-updated-when-you-send-me-your-estimates" id="toc-the-results---temporary-graph-to-be-updated-when-you-send-me-your-estimates" class="nav-link" data-scroll-target="#the-results---temporary-graph-to-be-updated-when-you-send-me-your-estimates">The Results - Temporary graph to be updated when you send me your estimates</a></li>
  <li><a href="#why-this-matters" id="toc-why-this-matters" class="nav-link" data-scroll-target="#why-this-matters">Why this matters</a></li>
  </ul>
</li>
  <li>
<a href="#repro-diagnosis" id="toc-repro-diagnosis" class="nav-link" data-scroll-target="#repro-diagnosis">Part 3 — Diagnosing a bad dataset and script</a>
  <ul class="collapse">
<li><a href="#data-quality-audit" id="toc-data-quality-audit" class="nav-link" data-scroll-target="#data-quality-audit">Data quality audit</a></li>
  <li><a href="#step-2-a-documented-cleaning-script" id="toc-step-2-a-documented-cleaning-script" class="nav-link" data-scroll-target="#step-2-a-documented-cleaning-script">Step 2 — A documented cleaning script</a></li>
  <li><a href="#tada-the-framework-behind-a-reviewable-script" id="toc-tada-the-framework-behind-a-reviewable-script" class="nav-link" data-scroll-target="#tada-the-framework-behind-a-reviewable-script">TADA: the framework behind a reviewable script</a></li>
  <li><a href="#step-3-build-the-readme-with-readmebuilder" id="toc-step-3-build-the-readme-with-readmebuilder" class="nav-link" data-scroll-target="#step-3-build-the-readme-with-readmebuilder">Step 3 — Build the README with READMEBuilder</a></li>
  </ul>
</li>
  <li>
<a href="#repro-sortee" id="toc-repro-sortee" class="nav-link" data-scroll-target="#repro-sortee">Part 5 — The SORTEE Guidelines and archiving</a>
  <ul class="collapse">
<li><a href="#pre-submission-checklist" id="toc-pre-submission-checklist" class="nav-link" data-scroll-target="#pre-submission-checklist">Pre-submission checklist</a></li>
  </ul>
</li>
  <li><a href="#glossary" id="toc-glossary" class="nav-link" data-scroll-target="#glossary">Glossary</a></li>
  <li><a href="#reading" id="toc-reading" class="nav-link" data-scroll-target="#reading">Reading</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-reproducibility.html">Day 2: Reproducibility</a></li><li class="breadcrumb-item"><a href="./06-reproducibility.html">Block 1: Reproducibility</a></li></ol></nav><div class="quarto-title">
<h1 class="title">Block 1: Reproducibility</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><blockquote class="blockquote">
<p><strong>Materials:</strong> Download all files from the course OSF page: <strong>https://osf.io/jgeq9/</strong> <strong>Files needed:</strong> <code>celegans_repro_raw.csv</code> and <code>celegans_repro_final.csv</code></p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Before we start:</strong> Download <code>celegans_repro_raw.csv</code> and <code>celegans_repro_final.csv</code> from https://osf.io/jgeq9/ and place them in your working directory. We will load them throughout the session.</p>
</div>
</div>
<hr>
<section id="repro-what" class="level2"><h2 class="anchored" data-anchor-id="repro-what">Part 1 — What is reproducibility?</h2>
<p><em>⏱ ~20 minutes</em></p>
<section id="analytical-and-computational-reproducibility" class="level3"><h3 class="anchored" data-anchor-id="analytical-and-computational-reproducibility">Analytical and computational reproducibility</h3>
<p>When scientists use the word “reproducibility” they often mean subtly different things. Being precise matters, because the solutions are different.</p>
<p>Goodman et al.&nbsp;(2016) distinguish three types. This chapter focuses on the two most directly within our control:</p>
<p><strong>Analytical reproducibility</strong> — given the same raw data, would a different analyst using the same stated methods reach the same conclusions? This is harder than it sounds. The methods section of a typical ecology or evolutionary biology paper leaves dozens of decisions underspecified. Which observations are excluded and why? How are missing values handled? Is a covariate log-transformed? What random effects structure is used? These “researcher degrees of freedom” (Simmons et al.&nbsp;2011) mean that even honest, well-intentioned analysts following the same broad methods can produce meaningfully different results.</p>
<p><strong>Computational reproducibility</strong> — given the same data <em>and</em> the same code, can someone else run it and get identical outputs? This is a lower bar than analytical reproducibility — it only asks “does your code actually do what you think it does?” — but it is the bar that the majority of published papers in ecology and evolutionary biology currently fail to clear.</p>
<p><strong>Replicability</strong> — does the finding hold when new data are independently collected? This is what most people mean by “the reproducibility crisis”, but it is also the hardest to address because it ultimately depends on whether the underlying effect is real.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Shorthand:</strong> Computational reproducibility asks “did you do what your code says?” Analytical reproducibility asks “would a reasonable analyst agree with your approach?” Replicability asks “does it still hold with new data?”</p>
</div>
</div>
</section><section id="the-replication-crisis-starts-with-reproducibility" class="level3"><h3 class="anchored" data-anchor-id="the-replication-crisis-starts-with-reproducibility">The replication crisis starts with reproducibility</h3>
<p>Across psychology, biomedicine, ecology and evolutionary biology, large-scale efforts to repeat published studies have found that a substantial share of findings do not hold up — the <strong>replication crisis</strong> (also called the <strong>reproducibility crisis</strong>, the two terms being used more or less interchangeably in public discussion).</p>
<p>It is tempting to treat this as purely a problem of <em>replicability</em> — of effects that were never real. But a finding cannot even be evaluated unless its analysis is reproducible in the first place. If the data and code are not available, or are available but do not run, nobody can check whether the published result actually follows from the data. A non-reproducible literature is one where genuine errors stay hidden, and where a failed replication cannot be diagnosed: was the original analysis wrong, or is the effect simply fragile? <strong>Lack of reproducibility is therefore both a problem in its own right and an upstream cause of the wider crisis</strong> — it removes the evidence trail we would need to tell sound science from artefact.</p>
<p>Reproducibility fails at several sequential stages of the analysis pipeline. The table below pulls together estimates from recent surveys at each stage; differences between studies reflect different journals, samples and time windows rather than disagreement about the underlying problem.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Reproducibility rates at four sequential stages of the analysis pipeline. Percentages are of all sampled papers unless noted; Trisovic et al. (2022) is a percentage of archived R files.</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Study (sample)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">% of papers</th>
</tr></thead>
<tbody>
<tr class="odd" data-grouplength="3">
<td colspan="2" style="border-bottom: 1px solid"><strong>Data archived</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Cooper et al. (2026) — 1,861 BES papers (2017–24)</td>
<td style="text-align: left;">90%</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Kambouris et al. (2024) — 177 EcoEvo meta-analyses (2015–17)</td>
<td style="text-align: left;">75%</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Kellner et al. (2025) — 497 papers, 9 ecology journals (2018–22)</td>
<td style="text-align: left;">50%</td>
</tr>
<tr class="odd" data-grouplength="4">
<td colspan="2" style="border-bottom: 1px solid"><strong>Code archived</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Kellner et al. (2025)</td>
<td style="text-align: left;">33%</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Cooper et al. (2026)</td>
<td style="text-align: left;">31%</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Culina et al. (2020) — ecology</td>
<td style="text-align: left;">27%</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Kambouris et al. (2024)</td>
<td style="text-align: left;">16%</td>
</tr>
<tr class="even" data-grouplength="2">
<td colspan="2" style="border-bottom: 1px solid"><strong>Code runs without error</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Trisovic et al. (2022) — 9,078 R files, Harvard Dataverse</td>
<td style="text-align: left;">26% (initial) / 44% (after auto-cleaning)</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Kellner et al. (2025)</td>
<td style="text-align: left;">7%</td>
</tr>
<tr class="odd" data-grouplength="1">
<td colspan="2" style="border-bottom: 1px solid"><strong>Target result reproduced</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Kambouris et al. (2024) — of 26 papers sharing both</td>
<td style="text-align: left;">27–73% (criterion-dependent)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The table makes two failure points concrete.</p>
<p><strong>First, the code is often simply not archived.</strong> Cooper et al.&nbsp;(2026), surveying 1,861 papers published 2017–2024 across the seven British Ecological Society journals, found that data archiving has become near-universal — 97% of papers that used data archived it, although that figure is held up by mandatory journal policies rather than community norms — but <strong>only 35% of papers that used code also archived it</strong> (about 31% of all sampled papers). The picture is similar or worse in samples without strong code-sharing mandates: Kellner et al.&nbsp;(2025), across nine ecology journals, found data <em>and</em> code available for only 28% of 497 papers; Kambouris et al.&nbsp;(2024) found data and code shared for only 15% of 177 ecology and evolutionary biology meta-analyses published 2015–17.</p>
<p><strong>Second, even when code is archived, it frequently does not run.</strong> Kellner et al.&nbsp;(2025) attempted to execute the R code accompanying those 497 papers and found <strong>only 7% of all papers — and only 27% of the papers that had archived data and code — ran without error</strong>. The most common causes were missing or misnamed files, missing R objects, and reliance on deprecated R packages (the retirement of <code>rgdal</code> and <code>maptools</code> alone broke 17 papers). Trisovic et al.&nbsp;(2022), executing more than 9,000 archived R files from the Harvard Dataverse, found 74% failed on the first attempt and 56% still failed after automated cleaning. Kambouris et al.&nbsp;(2024) successfully reproduced the target result from 27–73% of the 26 ecology and evolution meta-analyses that shared both data and code, the range depending on how strictly “successful reproduction” was defined.</p>
<p><strong>Documentation quality is the other half of the problem.</strong> Cooper et al.&nbsp;(2026) also recorded that around a third of papers had no README to explain their archived files, and that the quality of the READMEs that did exist varied substantially. Sharing rates have crept up over the last decade — from ~27% in Culina et al.&nbsp;(2020) to ~31–35% here — but the execution rate has not budged: the funnel is getting wider at the top while staying just as narrow at the bottom. Sharing is necessary but not sufficient — archived data and code also have to be <em>good enough to run and reproduce the result</em>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Opening activity — why don’t <em>you</em> share?</strong> <em>(type your answer in the chat)</em></p>
<p>Think about your most recent or current project.</p>
<ol type="1">
<li>Is the <strong>data</strong> publicly available? Is the <strong>code</strong>?</li>
<li>If either is not — why not? Be honest. Too busy? Worried someone will find an error? Not sure how or where? Worried about being scooped? Code too messy to show anyone?</li>
</ol>
<p>Write down your real reasons. Gomes et al.&nbsp;(2022) surveyed researchers and grouped the barriers people actually report — knowledge gaps, fear of scrutiny, time cost, misaligned career incentives. Keep your list; at the end of the session we will compare it with theirs.</p>
<blockquote class="blockquote">
<p><strong>Gomes, D.G.E., et al.&nbsp;(2022).</strong> Why don’t we share data and code? Perceived barriers and benefits to public archiving practices. <em>Proceedings of the Royal Society B</em>, 289, 20221113. https://doi.org/10.1098/rspb.2022.1113</p>
</blockquote>
</div>
</div>
<hr></section></section><section id="repro-multiverse" class="level2"><h2 class="anchored" data-anchor-id="repro-multiverse">Part 2 — Many analysts, many answers</h2>
<p><em>⏱ ~40 minutes</em></p>
<section id="background-the-garden-of-forking-paths" class="level3"><h3 class="anchored" data-anchor-id="background-the-garden-of-forking-paths">Background: the garden of forking paths</h3>
<p>Even when analysts work honestly with the same data and the same stated question, they can reach meaningfully different conclusions. Gelman &amp; Loken (2013) described this as “the garden of forking paths”: not deliberate p-hacking, but the way that the path through analytical decisions always looks inevitable in hindsight, even when it was one of many equally valid routes.</p>
<p>The most direct demonstration of this is the <strong>many analysts</strong> paradigm (Silberzahn et al.&nbsp;2018; Gould et al.&nbsp;2023). Multiple independent teams are each given the same dataset and the same question. They analyse it independently, then compare results.</p>
<p>Gould et al.&nbsp;(2023) also did this in ecology. Multiple teams given the same EcoEvo dataset produced a distribution of estimates and conclusions — large variability, no single “correct” answer, but some analyses better documented than others. The pattern is consistent: <strong>underspecified methods produce variable results</strong>, not because researchers are dishonest but because the analytical space is genuinely large.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/many_analysts.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>The Many Analysts project (Gould et al 2023)</figcaption></figure>
</div>
</div>
</div>
</section><section id="you-are-the-analyst" class="level3"><h3 class="anchored" data-anchor-id="you-are-the-analyst">You are the analyst</h3>
<p>Now you experience this directly. You are given the <em>C. elegans</em> reproduction dataset from the course OSF page and a deliberately vague question. Analyse it however seems most reasonable to you.</p>
<p><strong>The biology:</strong> <em>C. elegans</em> is a workhorse model organism in genetics and ageing research. The dataset records each worm’s <strong>total offspring</strong> — its lifetime reproductive output — from an experiment crossing two interventions:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>Variable</th>
<th>Meaning</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>worm_id</code></td>
<td>Individual worm identifier</td>
</tr>
<tr class="even">
<td><code>B</code></td>
<td>Batch (1–6) — worms run in separate cohorts</td>
</tr>
<tr class="odd">
<td><code>strain</code></td>
<td>
<code>daf</code> = daf-2 RNAi (knocks down insulin/IGF-1 signalling; extends lifespan and alters reproduction); <code>empty_vector</code> = control RNAi</td>
</tr>
<tr class="even">
<td><code>diet</code></td>
<td>
<code>AL</code> = ad libitum (fed freely); <code>EODF</code> = every-other-day fasting (dietary restriction)</td>
</tr>
<tr class="odd">
<td><code>TO</code></td>
<td>Total offspring — lifetime count of live progeny per worm</td>
</tr>
</tbody>
</table>
<p><strong>The question:</strong> <em>Does daf-2 RNAi affect reproduction?</em></p>
<p>That is all you are told. Now analyse it.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Individual activity (12 minutes)</strong></p>
<p>Load <code>celegans_repro_final.csv</code> from https://osf.io/jgeq9/ and answer: <strong>does daf-2 RNAi affect total offspring?</strong></p>
<p>You must decide:</p>
<ul>
<li>What to do with any unusual values in the data</li>
<li>Whether to include diet as a covariate or factor</li>
<li>Whether batch (<code>B</code>) should be a fixed or random effect, or ignored</li>
<li>What statistical model to use (t-test? linear model? mixed model? a count model such as a Poisson or negative-binomial GLMM?)</li>
<li>Whether to use <code>TO</code> as-is or transform it</li>
</ul>
<p><strong>Before running anything</strong>, write down your three most important analytical decisions and why. Then run your analysis.</p>
<p>Write your estimates in chat.</p>
<ol type="1">
<li>Your estimate for the daf vs empty_vector effect (with units — e.g.&nbsp;offspring per worm)</li>
<li>Significant or not? (yes/no)</li>
<li>Your three key decisions</li>
</ol>
</div>
</div>
</section><section id="reporting-on-the-same-scale-emmeans" class="level3"><h3 class="anchored" data-anchor-id="reporting-on-the-same-scale-emmeans">Reporting on the same scale: emmeans</h3>
<p>Different analysts will pick different models e.g.&nbsp;a Gaussian linear (or mixed) model, a Poisson GLMM, a negative-binomial GLMM, or a log-transformed linear model. Each one reports the <code>daf</code> effect on a different scale:</p>
<ul>
<li>A linear model on <code>TO</code> returns an <strong>additive difference</strong> — “daf reduces offspring by X per worm.”</li>
<li>A Poisson or NB GLMM with a log link returns a <strong>log-scale coefficient</strong>, which back-transforms to a <strong>rate ratio</strong> — “daf has 0.7× the offspring of controls.”</li>
<li>A linear model on <code>log(TO)</code> returns a log-scale difference, which back-transforms to a ratio.</li>
</ul>
<p>These numbers are not directly comparable across the room. <strong><code>emmeans</code></strong> puts them all on the response scale (offspring per worm) in two steps: compute the estimated marginal means, then take the pairwise contrast between <code>daf</code> and <code>empty_vector</code>. For log-link models we use <code>regrid()</code> first, which back-transforms the means to the response scale <strong>before</strong> the contrast — so the result is a <em>difference</em> in offspring, not the default rate ratio.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># install.packages("emmeans")</span></span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="co"># Works for lm, lmer, glmer, glmer.nb. regrid() back-transforms to the</span></span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="co"># response scale BEFORE the contrast. For identity-link models (lm/lmer)</span></span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="co"># it is effectively null; for log-link models (glmer/glmer.nb) it</span></span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="co"># converts the default rate ratio into a difference in offspring.</span></span>
<span id="cb1-8"><a href="#cb1-8"></a><span class="fu">emmeans</span>(model, <span class="sc">~</span> strain) <span class="sc">|&gt;</span></span>
<span id="cb1-9"><a href="#cb1-9"></a>  <span class="fu">regrid</span>() <span class="sc">|&gt;</span></span>
<span id="cb1-10"><a href="#cb1-10"></a>  <span class="fu">contrast</span>(<span class="st">"pairwise"</span>, <span class="at">adjust =</span> <span class="st">"none"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-11"><a href="#cb1-11"></a>  <span class="fu">confint</span>()</span>
<span id="cb1-12"><a href="#cb1-12"></a><span class="co">#  -&gt; "daf - empty_vector"   estimate   95% CI   in offspring per worm</span></span>
<span id="cb1-13"><a href="#cb1-13"></a></span>
<span id="cb1-14"><a href="#cb1-14"></a><span class="co"># If you fitted with a manual transformation, e.g. lm(log(TO) ~ strain),</span></span>
<span id="cb1-15"><a href="#cb1-15"></a><span class="co"># emmeans does NOT auto-detect the transform -- tell it explicitly:</span></span>
<span id="cb1-16"><a href="#cb1-16"></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(model, <span class="sc">~</span> strain) <span class="sc">|&gt;</span> <span class="fu">update</span>(<span class="at">tran =</span> <span class="st">"log"</span>)</span>
<span id="cb1-17"><a href="#cb1-17"></a>emm <span class="sc">|&gt;</span> <span class="fu">regrid</span>() <span class="sc">|&gt;</span> <span class="fu">contrast</span>(<span class="st">"pairwise"</span>) <span class="sc">|&gt;</span> <span class="fu">confint</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Report the <strong>estimate, the 95% confidence interval, and the units</strong> (offspring per worm). If you prefer a multiplicative effect, report a ratio as well — but at minimum everyone reports the difference on the response scale so the room is comparing like with like.</p>
</section><section id="the-results---temporary-graph-to-be-updated-when-you-send-me-your-estimates" class="level3"><h3 class="anchored" data-anchor-id="the-results---temporary-graph-to-be-updated-when-you-send-me-your-estimates">The Results - Temporary graph to be updated when you send me your estimates</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="06-reproducibility_files/figure-html/many-analysts-demo-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Results from the many-analysts activity. Each point is one participant’s estimate for the daf-2 RNAi effect on C. elegans total offspring.</figcaption></figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Debrief (5 minutes):</strong></p>
<ol type="1">
<li>How much did the estimates vary? Did anyone get a non-significant result while others got significant?</li>
<li>Who modelled batch as a random effect? Did that change the conclusion?</li>
<li>Who used a count model (Poisson / negative-binomial) vs a plain linear model? Does the model choice matter here?</li>
<li>What would the published literature look like if each of you submitted your analysis independently?</li>
</ol>
</div>
</div>
</section><section id="why-this-matters" class="level3"><h3 class="anchored" data-anchor-id="why-this-matters">Why this matters</h3>
<p>The variation you just observed is not noise — it is the direct consequence of underspecified methods. The solution is not to force everyone into the same analysis. The solution is <strong>transparency</strong>: document every analytical decision so that a reader can evaluate it, replicate it, and understand what would change if an alternative choice had been made.</p>
<p>This is where the SORTEE Guidelines (Pick et al.&nbsp;2026) and the TADA! framework (Ivimey-Cook et al.&nbsp;2025) come in — and it is also the problem that code review (next chapter) is designed to catch.</p>
<hr></section></section><section id="repro-diagnosis" class="level2"><h2 class="anchored" data-anchor-id="repro-diagnosis">Part 3 — Diagnosing a bad dataset and script</h2>
<p><em>⏱ ~30 minutes</em></p>
<p>Now we look systematically at the raw data file. <code>celegans_repro_raw.csv</code> contains the same experiment but before any cleaning. Every problem in it is a real type of problem that appears in published archives.</p>
<section id="data-quality-audit" class="level3"><h3 class="anchored" data-anchor-id="data-quality-audit">Data quality audit</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2"></a></span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="co"># Load the raw data — download from https://osf.io/jgeq9/</span></span>
<span id="cb2-4"><a href="#cb2-4"></a>dat_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"celegans_repro_raw.csv"</span>)</span>
<span id="cb2-5"><a href="#cb2-5"></a></span>
<span id="cb2-6"><a href="#cb2-6"></a><span class="co"># First look</span></span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="fu">dim</span>(dat_raw)</span>
<span id="cb2-8"><a href="#cb2-8"></a><span class="fu">glimpse</span>(dat_raw)</span>
<span id="cb2-9"><a href="#cb2-9"></a><span class="fu">summary</span>(dat_raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># Check each variable for problems</span></span>
<span id="cb3-2"><a href="#cb3-2"></a></span>
<span id="cb3-3"><a href="#cb3-3"></a><span class="co"># strain values</span></span>
<span id="cb3-4"><a href="#cb3-4"></a>dat_raw <span class="sc">|&gt;</span> <span class="fu">count</span>(strain)</span>
<span id="cb3-5"><a href="#cb3-5"></a></span>
<span id="cb3-6"><a href="#cb3-6"></a><span class="co"># Diet values</span></span>
<span id="cb3-7"><a href="#cb3-7"></a>dat_raw <span class="sc">|&gt;</span> <span class="fu">count</span>(diet)</span>
<span id="cb3-8"><a href="#cb3-8"></a></span>
<span id="cb3-9"><a href="#cb3-9"></a><span class="co"># TO (total offspring) range</span></span>
<span id="cb3-10"><a href="#cb3-10"></a>dat_raw <span class="sc">|&gt;</span></span>
<span id="cb3-11"><a href="#cb3-11"></a>  <span class="fu">summarise</span>(<span class="at">min =</span> <span class="fu">min</span>(TO, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-12"><a href="#cb3-12"></a>            <span class="at">max =</span> <span class="fu">max</span>(TO, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-13"><a href="#cb3-13"></a>            <span class="at">n_na =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(TO)))</span>
<span id="cb3-14"><a href="#cb3-14"></a></span>
<span id="cb3-15"><a href="#cb3-15"></a><span class="co"># worm_id problems</span></span>
<span id="cb3-16"><a href="#cb3-16"></a>dat_raw <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="fu">is.na</span>(worm_id))</span>
<span id="cb3-17"><a href="#cb3-17"></a></span>
<span id="cb3-18"><a href="#cb3-18"></a><span class="co"># Duplicate rows?</span></span>
<span id="cb3-19"><a href="#cb3-19"></a>dat_raw <span class="sc">|&gt;</span></span>
<span id="cb3-20"><a href="#cb3-20"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(worm_id)) <span class="sc">|&gt;</span></span>
<span id="cb3-21"><a href="#cb3-21"></a>  <span class="fu">group_by</span>(worm_id, B) <span class="sc">|&gt;</span></span>
<span id="cb3-22"><a href="#cb3-22"></a>  <span class="fu">filter</span>(<span class="fu">n</span>() <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-23"><a href="#cb3-23"></a>  <span class="fu">arrange</span>(worm_id)</span>
<span id="cb3-24"><a href="#cb3-24"></a></span>
<span id="cb3-25"><a href="#cb3-25"></a><span class="co"># Rows where everything is NA except TO</span></span>
<span id="cb3-26"><a href="#cb3-26"></a>dat_raw <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="fu">is.na</span>(strain))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Activity: data audit (10 minutes)</strong></p>
<p>Run the code above. The raw data contains at least <strong>eight distinct data quality problems</strong>. List every one you can find in the chat.</p>
<p>Hint: look carefully at capitalisation, spacing, impossible values, sentinel values, and structural oddities.</p>
</div>
</div>
<p>Here is what you should have found:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Data quality problems in celegans_repro_raw.csv</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">#</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Problem</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Column</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Detail</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Why it matters</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Mixed capitalisation in strain</td>
<td style="text-align: left;">`strain`</td>
<td style="text-align: left;">`daf` (n=117) and `DAF` (n=24) — same condition, will be treated as two groups</td>
<td style="text-align: left;">Inflates group count; DAF worms silently excluded or double-counted</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Trailing whitespace in strain</td>
<td style="text-align: left;">`strain`</td>
<td style="text-align: left;">`empty_vector ` (with trailing space) — will not match `empty_vector`</td>
<td style="text-align: left;">Three worms silently dropped or form a phantom third group</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Mixed capitalisation in diet</td>
<td style="text-align: left;">`diet`</td>
<td style="text-align: left;">`EODF` (n=144) and `eodf` (n=27) — same condition, two labels</td>
<td style="text-align: left;">Same problem as issue 1 — artificially splits dietary groups</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Impossible negative offspring count</td>
<td style="text-align: left;">`TO`</td>
<td style="text-align: left;">worm_id 112, B=5, daf, EODF: TO = -46</td>
<td style="text-align: left;">Biological impossibility (offspring cannot be negative); distorts means and any model</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Implausible extreme offspring count</td>
<td style="text-align: left;">`TO`</td>
<td style="text-align: left;">worm_id 47, B=4, daf, AL: TO = 2850 — likely a typo for 285 (brood size is typically ~250–350)</td>
<td style="text-align: left;">Will massively inflate mean offspring in the daf/AL group</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Sentinel value 9999 not documented</td>
<td style="text-align: left;">`TO`</td>
<td style="text-align: left;">Three worms with TO = 9999 — an undocumented code, almost certainly 'offspring not recorded'</td>
<td style="text-align: left;">If treated as a real offspring count it dramatically inflates the outcome</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">Missing worm_id</td>
<td style="text-align: left;">`worm_id`</td>
<td style="text-align: left;">Two rows in B=1, daf, EODF have worm_id = NA</td>
<td style="text-align: left;">Cannot link these observations back to individual worms</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">Junk rows (501–506)</td>
<td style="text-align: left;">All</td>
<td style="text-align: left;">Six rows where B, strain, and diet are all NA — only TO has a value</td>
<td style="text-align: left;">Probably data entry artefacts; will cause errors in grouped summaries</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">Duplicate rows in batch 2</td>
<td style="text-align: left;">All</td>
<td style="text-align: left;">worm_ids 13–24 and 73–84 appear twice; some empty_vector batch 2 rows also doubled</td>
<td style="text-align: left;">Artificially inflates sample size and gives false precision</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Issue 6 (TO = 9999) is a good example of a sentinel value — a number used to encode a special meaning, here almost certainly “offspring not recorded” (the count is missing for that worm). Sentinel codes like 9999, -999, or 0-for-missing are common in real data files; they are legitimate only if documented in a codebook and handled explicitly in code. If someone runs <code>mean(TO)</code> on the raw data without knowing what 9999 means, their result will be completely wrong.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Activity: compare raw and final (5 minutes)</strong></p>
<p>Now load <code>celegans_repro_final.csv</code> and compare it to the raw file:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>dat_raw   <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"celegans_repro_raw.csv"</span>)</span>
<span id="cb4-2"><a href="#cb4-2"></a>dat_final <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"celegans_repro_final.csv"</span>)</span>
<span id="cb4-3"><a href="#cb4-3"></a></span>
<span id="cb4-4"><a href="#cb4-4"></a><span class="co"># How many rows differ?</span></span>
<span id="cb4-5"><a href="#cb4-5"></a><span class="fu">cat</span>(<span class="st">"Raw rows:"</span>, <span class="fu">nrow</span>(dat_raw), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb4-6"><a href="#cb4-6"></a><span class="fu">cat</span>(<span class="st">"Final rows:"</span>, <span class="fu">nrow</span>(dat_final), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb4-7"><a href="#cb4-7"></a><span class="fu">cat</span>(<span class="st">"Difference:"</span>, <span class="fu">nrow</span>(dat_raw) <span class="sc">-</span> <span class="fu">nrow</span>(dat_final), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb4-8"><a href="#cb4-8"></a></span>
<span id="cb4-9"><a href="#cb4-9"></a><span class="co"># What strain values remain in each?</span></span>
<span id="cb4-10"><a href="#cb4-10"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Raw strains:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb4-11"><a href="#cb4-11"></a><span class="fu">print</span>(<span class="fu">count</span>(dat_raw, strain))</span>
<span id="cb4-12"><a href="#cb4-12"></a></span>
<span id="cb4-13"><a href="#cb4-13"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Final strains:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb4-14"><a href="#cb4-14"></a><span class="fu">print</span>(<span class="fu">count</span>(dat_final, strain))</span>
<span id="cb4-15"><a href="#cb4-15"></a></span>
<span id="cb4-16"><a href="#cb4-16"></a><span class="co"># Does the final still contain the problematic TO values?</span></span>
<span id="cb4-17"><a href="#cb4-17"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Final TO range:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb4-18"><a href="#cb4-18"></a>dat_final <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="at">min =</span> <span class="fu">min</span>(TO, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb4-19"><a href="#cb4-19"></a>                        <span class="at">max =</span> <span class="fu">max</span>(TO, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb4-20"><a href="#cb4-20"></a></span>
<span id="cb4-21"><a href="#cb4-21"></a>In the chat<span class="sc">:</span> does the final file still contain TO <span class="ot">=</span> <span class="sc">-</span><span class="dv">46</span>? TO <span class="ot">=</span> <span class="dv">2850</span>? What does this tell you about the cleaning that was done?</span>
<span id="cb4-22"><a href="#cb4-22"></a><span class="sc">:::</span></span>
<span id="cb4-23"><a href="#cb4-23"></a></span>
<span id="cb4-24"><a href="#cb4-24"></a>This is the key point<span class="sc">:</span> <span class="st">`</span><span class="at">celegans_repro_final.csv</span><span class="st">`</span> has had <span class="sc">*</span>some<span class="sc">*</span> issues <span class="fu">addressed</span> (the DAF capitalisation rows removed, some duplicates resolved) but not all of them. The <span class="sc">-</span><span class="dv">46</span> and <span class="dv">2850</span> values remain. This is a realistic example of partial cleaning — common <span class="cf">in</span> real archives, and a genuine reproducibility problem because it means different analysts working from the <span class="st">"final"</span> file will still handle these values differently.</span>
<span id="cb4-25"><a href="#cb4-25"></a></span>
<span id="cb4-26"><a href="#cb4-26"></a><span class="sc">---</span></span>
<span id="cb4-27"><a href="#cb4-27"></a></span>
<span id="cb4-28"><a href="#cb4-28"></a><span class="do">## Part 4 — Fixing it: The SORTEE Guidelines {#repro-fix}</span></span>
<span id="cb4-29"><a href="#cb4-29"></a></span>
<span id="cb4-30"><a href="#cb4-30"></a><span class="er">*</span>⏱ <span class="sc">~</span><span class="dv">45</span> minutes<span class="sc">*</span></span>
<span id="cb4-31"><a href="#cb4-31"></a></span>
<span id="cb4-32"><a href="#cb4-32"></a><span class="do">### The framework</span></span>
<span id="cb4-33"><a href="#cb4-33"></a></span>
<span id="cb4-34"><a href="#cb4-34"></a>The SORTEE <span class="fu">Guidelines</span> (Pick, Ivimey<span class="sc">-</span>Cook et al. <span class="dv">2026</span>) provide the broader framework covering data archiving, licensing, and peer review<span class="sc">:</span></span>
<span id="cb4-35"><a href="#cb4-35"></a></span>
<span id="cb4-36"><a href="#cb4-36"></a><span class="er">&gt;</span> <span class="er">**</span>Pick, J.L., et <span class="fu">al.</span> (<span class="dv">2026</span>).<span class="sc">**</span> The SORTEE guidelines <span class="cf">for</span> data and code quality control <span class="cf">in</span> ecology and evolutionary biology. <span class="sc">*</span>Peer Community Journal<span class="sc">*</span>. https<span class="sc">:</span><span class="er">//</span>doi.org<span class="sc">/</span><span class="fl">10.24072</span><span class="sc">/</span>pcjournal<span class="fl">.687</span></span>
<span id="cb4-37"><a href="#cb4-37"></a></span>
<span id="cb4-38"><a href="#cb4-38"></a><span class="do">### Step 1 — Set up the project structure</span></span>
<span id="cb4-39"><a href="#cb4-39"></a></span>
<span id="cb4-40"><a href="#cb4-40"></a>Most analysis projects do not start tidy. Here is a <span class="st">"probably very likely"</span> folder structure <span class="cf">for</span> this <span class="sc">*</span>C. elegans<span class="sc">*</span> experiment — everything dumped <span class="cf">in</span> a single directory<span class="sc">:</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>REPROCODE_ANALYSIS/ ├── celegans_repro_raw.csv # raw data ├── celegans_repro_final.csv # a “cleaned” copy — but cleaned how? ├── ANALYSIS.R # the analysis script ├── old_code.R # an earlier version, still sitting here ├── celegans_analysis.Rmd # a write-up ├── celegans_analysis.html # the rendered write-up ├── final.jpg ├── finalplot.jpeg # “finalplot” — so which figure is current? ├── ExtractedFigure1.png └── 4Rs.jpg</p>
<pre><code>
This is a **bad structure**, and it is completely normal — most projects look like this. Nothing separates raw data from processed data, so you cannot tell which file is safe to overwrite or how `celegans_repro_final.csv` was produced. `old_code.R` is dead code left lying around; it invites a collaborator to run the wrong script. The four loose image files are generated outputs mixed in with the source, and names like `finalplot.jpeg` are version control by filename — undocumented and unreproducible. There is no README, so nothing tells a newcomer what to run, or in what order. (We review `ANALYSIS.R` itself in the code review chapter this afternoon — for now we fix the *structure*.)

Here is the structure to aim for instead — a few standard folders that separate inputs, code and outputs:


::: {.cell layout-align="center"}

```{.r .cell-code}
library(tidyverse)
library(here)

# Create a proper folder structure
dirs &lt;- c("data/raw", "data/processed", "analysis", "figures", "results")
for (d in dirs) {
  dir.create(d, recursive = TRUE, showWarnings = FALSE)
}

# Copy the raw data file into data/raw/ — never modify this copy
file.copy("celegans_repro_raw.csv",
          here("data", "raw", "celegans_repro_raw.csv"))

cat("Project structure:\n")
list.files(recursive = TRUE, include.dirs = TRUE)</code></pre>
</div>
</div>
</section><section id="step-2-a-documented-cleaning-script" class="level3"><h3 class="anchored" data-anchor-id="step-2-a-documented-cleaning-script">Step 2 — A documented cleaning script</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># analysis/01_data_cleaning.R</span></span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="co"># Author:   [your name]</span></span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="co"># Date:     [today]</span></span>
<span id="cb6-4"><a href="#cb6-4"></a><span class="co"># Purpose:  Clean raw C. elegans reproduction data for daf-2 × diet experiment</span></span>
<span id="cb6-5"><a href="#cb6-5"></a><span class="co">#</span></span>
<span id="cb6-6"><a href="#cb6-6"></a><span class="co"># Study:    Effect of daf-2 RNAi and dietary restriction on total offspring</span></span>
<span id="cb6-7"><a href="#cb6-7"></a><span class="co"># Organism: Caenorhabditis elegans (N2 background)</span></span>
<span id="cb6-8"><a href="#cb6-8"></a><span class="co"># Design:   2 strains (daf-2 RNAi vs empty_vector control) ×</span></span>
<span id="cb6-9"><a href="#cb6-9"></a><span class="co">#           2 diets (AL = ad libitum; EODF = every-other-day fasting)</span></span>
<span id="cb6-10"><a href="#cb6-10"></a><span class="co">#           6 batches (B); multiple worms per batch</span></span>
<span id="cb6-11"><a href="#cb6-11"></a><span class="co">#</span></span>
<span id="cb6-12"><a href="#cb6-12"></a><span class="co"># Variables:</span></span>
<span id="cb6-13"><a href="#cb6-13"></a><span class="co">#   worm_id   — individual worm ID (integer)</span></span>
<span id="cb6-14"><a href="#cb6-14"></a><span class="co">#   B         — batch number (1–6); should be treated as random effect</span></span>
<span id="cb6-15"><a href="#cb6-15"></a><span class="co">#   strain — "daf" = daf-2 RNAi; "empty_vector" = control</span></span>
<span id="cb6-16"><a href="#cb6-16"></a><span class="co">#   diet      — "AL" = ad libitum; "EODF" = every-other-day fasting</span></span>
<span id="cb6-17"><a href="#cb6-17"></a><span class="co">#   TO        — total offspring (count); 9999 = undocumented code for "not recorded"</span></span>
<span id="cb6-18"><a href="#cb6-18"></a><span class="co">#</span></span>
<span id="cb6-19"><a href="#cb6-19"></a><span class="co"># Input:  data/raw/celegans_repro_raw.csv</span></span>
<span id="cb6-20"><a href="#cb6-20"></a><span class="co"># Output: data/processed/celegans_clean.csv</span></span>
<span id="cb6-21"><a href="#cb6-21"></a><span class="co">#         results/exclusion_log.csv</span></span>
<span id="cb6-22"><a href="#cb6-22"></a></span>
<span id="cb6-23"><a href="#cb6-23"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb6-24"><a href="#cb6-24"></a><span class="fu">library</span>(here)</span>
<span id="cb6-25"><a href="#cb6-25"></a></span>
<span id="cb6-26"><a href="#cb6-26"></a><span class="co"># ── 1. Load ───────────────────────────────────────────────────────────────────</span></span>
<span id="cb6-27"><a href="#cb6-27"></a>dat_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"raw"</span>, <span class="st">"celegans_repro_raw.csv"</span>),</span>
<span id="cb6-28"><a href="#cb6-28"></a>                    <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-29"><a href="#cb6-29"></a><span class="fu">cat</span>(<span class="st">"Raw data:"</span>, <span class="fu">nrow</span>(dat_raw), <span class="st">"rows</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb6-30"><a href="#cb6-30"></a></span>
<span id="cb6-31"><a href="#cb6-31"></a><span class="co"># ── 2. Standardise factor levels (case and whitespace) ────────────────────────</span></span>
<span id="cb6-32"><a href="#cb6-32"></a><span class="co"># strain: "DAF" is a capitalisation error — same as "daf"</span></span>
<span id="cb6-33"><a href="#cb6-33"></a><span class="co"># "empty_vector " has trailing whitespace — same as "empty_vector"</span></span>
<span id="cb6-34"><a href="#cb6-34"></a><span class="co"># diet: "eodf" is a capitalisation error — same as "EODF"</span></span>
<span id="cb6-35"><a href="#cb6-35"></a>dat_std <span class="ot">&lt;-</span> dat_raw <span class="sc">|&gt;</span></span>
<span id="cb6-36"><a href="#cb6-36"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-37"><a href="#cb6-37"></a>    <span class="at">strain =</span> <span class="fu">str_trim</span>(<span class="fu">str_to_lower</span>(strain)),</span>
<span id="cb6-38"><a href="#cb6-38"></a>    <span class="at">diet      =</span> <span class="fu">str_trim</span>(<span class="fu">str_to_upper</span>(diet))</span>
<span id="cb6-39"><a href="#cb6-39"></a>  )</span>
<span id="cb6-40"><a href="#cb6-40"></a></span>
<span id="cb6-41"><a href="#cb6-41"></a><span class="fu">cat</span>(<span class="st">"After standardisation — strain values:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb6-42"><a href="#cb6-42"></a><span class="fu">print</span>(<span class="fu">count</span>(dat_std, strain))</span>
<span id="cb6-43"><a href="#cb6-43"></a><span class="fu">cat</span>(<span class="st">"After standardisation — diet values:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb6-44"><a href="#cb6-44"></a><span class="fu">print</span>(<span class="fu">count</span>(dat_std, diet))</span>
<span id="cb6-45"><a href="#cb6-45"></a></span>
<span id="cb6-46"><a href="#cb6-46"></a><span class="co"># ── 3. Count structural junk rows ───────────────────────────────────────────</span></span>
<span id="cb6-47"><a href="#cb6-47"></a><span class="co"># Rows 501–506: worm_id &gt; 500 with NA strain/diet — data entry artefacts</span></span>
<span id="cb6-48"><a href="#cb6-48"></a>n_junk <span class="ot">&lt;-</span> <span class="fu">sum</span>(dat_std<span class="sc">$</span>worm_id <span class="sc">&gt;=</span> <span class="dv">500</span> <span class="sc">&amp;</span> <span class="fu">is.na</span>(dat_std<span class="sc">$</span>strain),</span>
<span id="cb6-49"><a href="#cb6-49"></a>              <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-50"><a href="#cb6-50"></a><span class="fu">cat</span>(<span class="st">"Junk rows (worm_id &gt;= 500, NA strain):"</span>, n_junk, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb6-51"><a href="#cb6-51"></a></span>
<span id="cb6-52"><a href="#cb6-52"></a><span class="co"># ── 4. Remove junk and duplicate rows ──────────────────────────────────────────────────</span></span>
<span id="cb6-53"><a href="#cb6-53"></a><span class="co"># Batch 2 rows appear duplicated — retain first occurrence only</span></span>
<span id="cb6-54"><a href="#cb6-54"></a>dat_std <span class="ot">&lt;-</span> dat_std <span class="sc">|&gt;</span></span>
<span id="cb6-55"><a href="#cb6-55"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(<span class="fu">is.na</span>(strain) <span class="sc">&amp;</span> <span class="fu">is.na</span>(diet)))</span>
<span id="cb6-56"><a href="#cb6-56"></a></span>
<span id="cb6-57"><a href="#cb6-57"></a>n_before_dedup <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dat_std)</span>
<span id="cb6-58"><a href="#cb6-58"></a>dat_std <span class="ot">&lt;-</span> dat_std <span class="sc">|&gt;</span></span>
<span id="cb6-59"><a href="#cb6-59"></a>  <span class="fu">distinct</span>(worm_id, B, strain, diet, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-60"><a href="#cb6-60"></a>n_removed_dupes <span class="ot">&lt;-</span> n_before_dedup <span class="sc">-</span> <span class="fu">nrow</span>(dat_std)</span>
<span id="cb6-61"><a href="#cb6-61"></a><span class="fu">cat</span>(<span class="st">"Duplicate rows removed:"</span>, n_removed_dupes, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb6-62"><a href="#cb6-62"></a></span>
<span id="cb6-63"><a href="#cb6-63"></a><span class="co"># ── 5. Data-quality exclusions ───────────────────────────────────────────────</span></span>
<span id="cb6-64"><a href="#cb6-64"></a><span class="co"># Exclusion 1: TO = 9999 — undocumented sentinel meaning "offspring not</span></span>
<span id="cb6-65"><a href="#cb6-65"></a><span class="co"># recorded". These are missing values, not real counts of zero; we exclude</span></span>
<span id="cb6-66"><a href="#cb6-66"></a><span class="co"># them and record the count so the loss is visible in the methods section.</span></span>
<span id="cb6-67"><a href="#cb6-67"></a>n_missing <span class="ot">&lt;-</span> <span class="fu">sum</span>(dat_std<span class="sc">$</span>TO <span class="sc">==</span> <span class="dv">9999</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-68"><a href="#cb6-68"></a><span class="fu">cat</span>(<span class="st">"Missing offspring (TO = 9999):"</span>, n_missing, <span class="st">"excluded</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb6-69"><a href="#cb6-69"></a></span>
<span id="cb6-70"><a href="#cb6-70"></a><span class="co"># Exclusion 2: TO &lt; 0 — biologically impossible (offspring cannot be negative)</span></span>
<span id="cb6-71"><a href="#cb6-71"></a><span class="co"># worm_id 112, B=5, daf, EODF: TO = -46 — likely data entry error</span></span>
<span id="cb6-72"><a href="#cb6-72"></a>n_neg <span class="ot">&lt;-</span> <span class="fu">sum</span>(dat_std<span class="sc">$</span>TO <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-73"><a href="#cb6-73"></a><span class="fu">cat</span>(<span class="st">"Negative TO values:"</span>, n_neg, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb6-74"><a href="#cb6-74"></a></span>
<span id="cb6-75"><a href="#cb6-75"></a><span class="co"># Exclusion 3: TO &gt; 1000 and &lt; 9999 — implausible (C. elegans brood size is</span></span>
<span id="cb6-76"><a href="#cb6-76"></a><span class="co"># typically ~250–350; values in the thousands are not credible)</span></span>
<span id="cb6-77"><a href="#cb6-77"></a><span class="co"># worm_id 47, B=4, daf, AL: TO = 2850 — likely a typo for 285</span></span>
<span id="cb6-78"><a href="#cb6-78"></a><span class="co"># Flag rather than silently remove — needs verification with original data sheet</span></span>
<span id="cb6-79"><a href="#cb6-79"></a>n_implausible <span class="ot">&lt;-</span> <span class="fu">sum</span>(dat_std<span class="sc">$</span>TO <span class="sc">&gt;</span> <span class="dv">1000</span> <span class="sc">&amp;</span> dat_std<span class="sc">$</span>TO <span class="sc">&lt;</span> <span class="dv">9999</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-80"><a href="#cb6-80"></a><span class="fu">cat</span>(<span class="st">"Implausible TO values (&gt;1000, &lt;9999):"</span>, n_implausible,</span>
<span id="cb6-81"><a href="#cb6-81"></a>    <span class="st">"— flagged; excluded pending verification</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb6-82"><a href="#cb6-82"></a></span>
<span id="cb6-83"><a href="#cb6-83"></a>dat_clean <span class="ot">&lt;-</span> dat_std <span class="sc">|&gt;</span></span>
<span id="cb6-84"><a href="#cb6-84"></a>  <span class="fu">filter</span>(</span>
<span id="cb6-85"><a href="#cb6-85"></a>    TO <span class="sc">!=</span> <span class="dv">9999</span>,          <span class="co"># Exclusion 1: missing (9999 sentinel)</span></span>
<span id="cb6-86"><a href="#cb6-86"></a>    TO <span class="sc">&gt;=</span> <span class="dv">0</span>,             <span class="co"># Exclusion 2: impossible</span></span>
<span id="cb6-87"><a href="#cb6-87"></a>    TO <span class="sc">&lt;=</span> <span class="dv">1000</span>           <span class="co"># Exclusion 3: implausible</span></span>
<span id="cb6-88"><a href="#cb6-88"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb6-89"><a href="#cb6-89"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-90"><a href="#cb6-90"></a>    <span class="co"># Explicit factor with reference levels</span></span>
<span id="cb6-91"><a href="#cb6-91"></a>    <span class="at">strain =</span> <span class="fu">factor</span>(strain,</span>
<span id="cb6-92"><a href="#cb6-92"></a>                       <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"empty_vector"</span>, <span class="st">"daf"</span>)),</span>
<span id="cb6-93"><a href="#cb6-93"></a>    <span class="at">diet      =</span> <span class="fu">factor</span>(diet, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"AL"</span>, <span class="st">"EODF"</span>)),</span>
<span id="cb6-94"><a href="#cb6-94"></a>    <span class="at">B         =</span> <span class="fu">factor</span>(B)  <span class="co"># batch as factor for random effect</span></span>
<span id="cb6-95"><a href="#cb6-95"></a>  )</span>
<span id="cb6-96"><a href="#cb6-96"></a></span>
<span id="cb6-97"><a href="#cb6-97"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Final clean dataset:"</span>, <span class="fu">nrow</span>(dat_clean), <span class="st">"worms</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb6-98"><a href="#cb6-98"></a></span>
<span id="cb6-99"><a href="#cb6-99"></a><span class="co"># ── 6. Save ───────────────────────────────────────────────────────────────────</span></span>
<span id="cb6-100"><a href="#cb6-100"></a><span class="fu">write_csv</span>(dat_clean, <span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"processed"</span>, <span class="st">"celegans_clean.csv"</span>))</span>
<span id="cb6-101"><a href="#cb6-101"></a></span>
<span id="cb6-102"><a href="#cb6-102"></a>exclusion_log <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb6-103"><a href="#cb6-103"></a>  <span class="sc">~</span>Criterion,                                       <span class="sc">~</span>N,</span>
<span id="cb6-104"><a href="#cb6-104"></a>  <span class="st">"Junk rows (worm_id &gt;= 500, no strain/diet)"</span>,  n_junk,</span>
<span id="cb6-105"><a href="#cb6-105"></a>  <span class="st">"Duplicate rows removed"</span>,                          n_removed_dupes,</span>
<span id="cb6-106"><a href="#cb6-106"></a>  <span class="st">"Missing offspring (TO = 9999)"</span>,                  n_missing,</span>
<span id="cb6-107"><a href="#cb6-107"></a>  <span class="st">"Impossible count (TO &lt; 0)"</span>,                      n_neg,</span>
<span id="cb6-108"><a href="#cb6-108"></a>  <span class="st">"Implausible count (TO &gt; 1000, not 9999)"</span>,        n_implausible</span>
<span id="cb6-109"><a href="#cb6-109"></a>)</span>
<span id="cb6-110"><a href="#cb6-110"></a><span class="fu">write_csv</span>(exclusion_log, <span class="fu">here</span>(<span class="st">"results"</span>, <span class="st">"exclusion_log.csv"</span>))</span>
<span id="cb6-111"><a href="#cb6-111"></a><span class="fu">print</span>(exclusion_log)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Activity: run and inspect the cleaning script (8 minutes)</strong></p>
<p>Copy this script into <code>analysis/01_data_cleaning.R</code> in your project and run it.</p>
<p>Then answer in the chat:</p>
<ol type="1">
<li>How many worms are in the final clean dataset?</li>
<li>Looking at the exclusion log: which exclusion removes the most observations?</li>
<li>The script flags TO = 2850 as “pending verification” rather than silently removing or including it. Why is this the correct approach from a reproducibility standpoint?</li>
<li>Read through the cleaning script, do you understand what it is doing?</li>
</ol>
</div>
</div>
</section><section id="tada-the-framework-behind-a-reviewable-script" class="level3"><h3 class="anchored" data-anchor-id="tada-the-framework-behind-a-reviewable-script">TADA: the framework behind a reviewable script</h3>
<p>The cleaning script you just ran isn’t long, but several of the choices in it weren’t arbitrary — the header block, the <code>here()</code> calls, the explicit exclusion log, the section dividers. These map onto a small set of principles for analytical code sharing that will become a backbone for the rest of this course.</p>
<p>Ivimey-Cook et al.&nbsp;(2025) propose <strong>TADA</strong> — <em>Transferable, Available, Documented, Annotated</em> — as a minimum standard for analytical code accompanying published research. It complements the FAIR principles (which were designed mainly for data and software) by addressing the things that specifically go wrong with analysis scripts. The four letters:</p>
<ul>
<li>
<strong>T — Transferable.</strong> Code runs on someone else’s machine without modification. Concretely: no hard-coded absolute paths (use <code>here()</code> or relative paths from a project root), all packages declared at the top of the script, random seeds set before stochastic steps, software versions recorded somewhere reproducible (<code><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo()</a></code> output, <code>renv.lock</code>, or similar).</li>
<li>
<strong>A — Available.</strong> Code is deposited in a persistent, citable archive with a stable identifier — a Zenodo DOI minted from a tagged GitHub release, an OSF project, or a Dryad submission — and released under an explicit licence. “Available on request” and a personal Dropbox link are not TADA-compliant; the first decays with careers, the second decays with subscriptions.</li>
<li>
<strong>D — Documented.</strong> A README (at the project root) tells a reviewer what the code does, what each file is for, the order to run files in, where the input data live, what outputs are produced, and what software versions were used. We’ll build one of these in the next section using READMEBuilder.</li>
<li>
<strong>A — Annotated.</strong> Inline comments inside the scripts explain <em>why</em> a choice was made, not just <em>what</em> the line does. The cleaning script’s exclusion comments — <em>“TO = 9999 — undocumented sentinel meaning ‘offspring not recorded’… we exclude them and record the count so the loss is visible in the methods section”</em> — are annotation; <code># read the data</code> next to <code>read_csv()</code> is not.</li>
</ul>
<p>The order matters: a script can be perfectly annotated and still unrunnable on another machine because of a hard-coded path. A perfectly transferable script can still be unreviewable if there is no README explaining which of the seven files in the repository to run first. TADA forces all four to be in place.</p>
<p>This is why TADA comes before code review. Code review evaluates whether code is <em>Reported, Runs, Reliable, Reproducible</em> (the four Rs of Ivimey-Cook et al.&nbsp;2023, which we cover this afternoon). But if the code isn’t TADA-compliant in the first place — if it won’t transfer, isn’t available, has no documentation, or isn’t annotated — there is nothing for a reviewer to evaluate. TADA is what makes code reviewable; the review itself comes later.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Map TADA onto the cleaning script</strong> <em>(5 minutes — type in chat)</em></p>
<p>Scroll back to <code>01_data_cleaning.R</code>. Identify one specific line or block that demonstrates each of the four TADA principles. One of them is only <em>partially</em> present in the script as it stands — which, and what’s missing? <em>Try to answer before reading the next paragraph.</em></p>
</div>
</div>
<p><strong>Answer.</strong> <strong>Available</strong> is the partial one. The script is <em>written</em> in a way that could be archived, but on its own a script is not Available — that requires deposit (Zenodo, OSF, Dryad) with a DOI and a licence. We close that gap in Part 5.</p>
</section><section id="step-3-build-the-readme-with-readmebuilder" class="level3"><h3 class="anchored">Step 3 — Build the README with READMEBuilder</h3>
<p>A README is the single most useful file in an archive for anyone trying to reuse it — and it is exactly the file that gets skipped under deadline pressure. Writing one from a blank page is hard; filling in a structured form is not.</p>
<p><strong>READMEBuilder</strong> is a Shiny app that removes that friction. It walks you through the sections a good README needs — overview, directory map, data dictionary, known issues, licensing, reproduction steps — as a guided form, then exports a clean, consistently formatted <code>README.md</code>. Because the structure is fixed, every README it produces already satisfies the <em>Documented</em> requirement of TADA!. It does not write the <em>content</em> for you — you still have to know your data — but it guarantees nothing structural is forgotten. Link here: https://github.com/EIvimeyCook/READMEBuilder</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>READMEBuilder</strong> is a Shiny app / R package for assembling TADA-compliant READMEs from a guided form. Launch the app (your instructor will share the link) or run it locally if you have the package installed.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Activity: build the README (10 minutes)</strong></p>
<p>Open <strong>READMEBuilder</strong> and complete a README for the C. elegans project. The app asks for the sections shown in the template below — the hardest is the data dictionary, so focus there: can you complete every row?</p>
<p>If you cannot get the app running, fill in the template by hand — the fields are identical.</p>
<section id="c.-elegans-strain-diet-reproduction-experiment" class="level1"><h1>C. elegans strain × diet reproduction experiment</h1>
<section id="authors" class="level2"><h2 class="anchored" data-anchor-id="authors">Authors</h2>
<ul>
<li>[Name] ([ORCID]), [Affiliation]</li>
</ul>
<p><strong>OSF project:</strong> https://osf.io/jgeq9/</p>
</section><section id="overview" class="level2"><h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>[2–3 sentences: what is the experiment, what question does it address, what does this archive contain]</p>
</section><section id="repository-contents" class="level2"><h2 class="anchored" data-anchor-id="repository-contents">Repository contents</h2>
<p>. ├── data/ │ ├── raw/ # Original unmodified data │ └── processed/ # Cleaned data (produced by 01_data_cleaning.R) ├── analysis/ │ ├── 01_data_cleaning.R │ └── 02_analysis.R ├── results/ ├── figures/ └── README.md</p>
</section><section id="data-dictionary-datarawcelegans_repro_raw.csv" class="level2"><h2 class="anchored" data-anchor-id="data-dictionary-datarawcelegans_repro_raw.csv">Data dictionary — <code>data/raw/celegans_repro_raw.csv</code>
</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead><tr class="header">
<th>Variable</th>
<th>Type</th>
<th>Units</th>
<th>Description</th>
<th>Notes</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>worm_id</td>
<td>integer</td>
<td>—</td>
<td></td>
<td>Some NAs in batch 1</td>
</tr>
<tr class="even">
<td>B</td>
<td>integer</td>
<td>—</td>
<td>Batch number (1–6)</td>
<td>Should be treated as random effect</td>
</tr>
<tr class="odd">
<td>strain</td>
<td>character</td>
<td>—</td>
<td></td>
<td>“DAF” = capitalisation error for “daf”</td>
</tr>
<tr class="even">
<td>diet</td>
<td>character</td>
<td>—</td>
<td></td>
<td>“eodf” = capitalisation error for “EODF”</td>
</tr>
<tr class="odd">
<td>TO</td>
<td>integer</td>
<td>offspring</td>
<td></td>
<td>9999 = undocumented code for “not recorded”</td>
</tr>
</tbody>
</table></section><section id="known-data-quality-issues-raw-file" class="level2"><h2 class="anchored" data-anchor-id="known-data-quality-issues-raw-file">Known data quality issues (raw file)</h2>
<p>[List the issues you found in the audit]</p>
</section><section id="how-to-reproduce" class="level2"><h2 class="anchored" data-anchor-id="how-to-reproduce">How to reproduce</h2>
<p>source(“analysis/01_data_cleaning.R”) source(“analysis/02_analysis.R”)</p>
</section><section id="licence" class="level2"><h2 class="anchored" data-anchor-id="licence">Licence</h2>
<p>Data: CC BY 4.0 Code: MIT</p>
<p>Export the <code>README.md</code> from READMEBuilder into your project root, then paste your “Overview” paragraph and your completed data dictionary into the chat.</p>
</section></section>
</div>
</div>
<hr></section></section><section id="repro-sortee" class="level2"><h2 class="anchored" data-anchor-id="repro-sortee">Part 5 — The SORTEE Guidelines and archiving</h2>
<p><em>⏱ ~15 minutes</em></p>
<p>TADA! sets the floor for code sharing (Part 4). The SORTEE Guidelines build on this with the full quality control framework — including data archiving, licensing, and the relationship between open data and peer review (Pick et al.&nbsp;2026). Two practical points for right now:</p>
<p><strong>Licensing.</strong> Without a licence, all rights are reserved by default — others cannot legally reuse your data or code even if you intend them to. Add to every archive (these are some typical ones):</p>
<p>Data: CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/) Code: MIT (https://opensource.org/licenses/MIT)</p>
<p><strong>Persistent archiving.</strong> The OSF page at https://osf.io/jgeq9/ is itself a public archive — it has a stable URL. However, you can edit and remove the repository. The best method is to use GitHub and connect with Zenodo or Figshare and create a permanent URL and formal DOI. We cover GitHub later.</p>
<section id="pre-submission-checklist" class="level3"><h3 class="anchored" data-anchor-id="pre-submission-checklist">Pre-submission checklist</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Pre-submission checklist: TADA! + SORTEE Guidelines</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Done</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Item</th>
</tr></thead>
<tbody>
<tr class="odd" data-grouplength="5">
<td colspan="2" style="border-bottom: 1px solid"><strong>TADA! minimum</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">Cleaning Code saved as .R (not in Word, PDF, or notebook output only)</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">All file paths relative — using here() or an RStudio project</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">Cleaning Code publicly archived with a persistent DOI</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">README: directory map, data dictionary, known issues, reproduction guide</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">Comments explain *why* every cleaning decision was made</td>
</tr>
<tr class="odd" data-grouplength="3">
<td colspan="2" style="border-bottom: 1px solid"><strong>Data</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">Raw data preserved unmodified in data/raw/</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">All exclusion criteria coded and counts saved to exclusion_log.csv</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">Sentinel values (e.g. 9999) documented in a codebook, not silently dropped</td>
</tr>
<tr class="odd" data-grouplength="2">
<td colspan="2" style="border-bottom: 1px solid"><strong>Code</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">Scripts numbered; run in sequence from a fresh session without errors</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">Package versions recorded (renv.lock or saved sessionInfo())</td>
</tr>
<tr class="even" data-grouplength="3">
<td colspan="2" style="border-bottom: 1px solid"><strong>Archiving</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">Data archived with a persistent DOI</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">Licence stated for data (CC BY / CC0) and code (MIT / GPL)</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">DOI cited in the Data Availability Statement</td>
</tr>
<tr class="even" data-grouplength="1">
<td colspan="2" style="border-bottom: 1px solid"><strong>Code review</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">☐</td>
<td style="text-align: left;">Code reviewed by at least one other person before submission</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Closing reflection</strong> <em>(type in chat)</em></p>
<p>Return to your opening activity — the barriers you listed for not sharing data and code. Look at them again alongside the benefits and reframings in Gomes et al.&nbsp;(2022). Which barrier is the real blocker for you?</p>
<p>Complete this sentence: “Before my next submission, the one thing I will do differently is…”</p>
</div>
</div>
<hr></section></section><section id="glossary" class="level2"><h2 class="anchored" data-anchor-id="glossary">Glossary</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Term</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Analytical reproducibility</td>
<td style="text-align: left;">Different analysts following the same stated methods reach the same conclusions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Computational reproducibility</td>
<td style="text-align: left;">The same code and data produce identical outputs when run by another person</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many analysts paradigm</td>
<td style="text-align: left;">Multiple independent teams analyse the same dataset to quantify analytical variability</td>
</tr>
<tr class="even">
<td style="text-align: left;">Researcher degrees of freedom</td>
<td style="text-align: left;">The space of defensible analytical decisions in an underspecified analysis (Simmons et al. 2011)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Garden of forking paths</td>
<td style="text-align: left;">The metaphor for multiple valid analytical paths through any dataset (Gelman &amp; Loken 2013)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sentinel value</td>
<td style="text-align: left;">A special number used to encode meaning, e.g. 9999 standing in for 'not recorded'; must be documented and handled explicitly</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TADA!</td>
<td style="text-align: left;">Transferable, Available, Documented, Annotated — minimum code sharing requirements (Ivimey-Cook et al. 2025)</td>
</tr>
<tr class="even">
<td style="text-align: left;">FAIR</td>
<td style="text-align: left;">Findable, Accessible, Interoperable, Reusable — principles for open research data (Wilkinson et al. 2016)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SORTEE</td>
<td style="text-align: left;">Society for Open, Reliable, and Transparent Ecology and Evolutionary Biology</td>
</tr>
<tr class="even">
<td style="text-align: left;">Replication crisis</td>
<td style="text-align: left;">The finding that many published results fail when independently repeated; also called the reproducibility crisis</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CC BY 4.0</td>
<td style="text-align: left;">Creative Commons Attribution — reuse permitted with attribution</td>
</tr>
<tr class="even">
<td style="text-align: left;">MIT</td>
<td style="text-align: left;">Permissive open-source code licence requiring only attribution</td>
</tr>
</tbody>
</table>
</div>
</div>
<hr></section><section id="reading" class="level2"><h2 class="anchored" data-anchor-id="reading">Reading</h2>
<ul>
<li>
<strong>Ivimey-Cook, E.R., et al.&nbsp;(2025).</strong> TADA! https://doi.org/10.32942/X2D93K</li>
<li>
<strong>Pick, J.L., et al.&nbsp;(2026).</strong> SORTEE Guidelines. https://doi.org/10.24072/pcjournal.687</li>
<li>
<strong>Silberzahn, R., et al.&nbsp;(2018).</strong> Many analysts, one dataset. <em>Advances in Methods</em>. https://doi.org/10.1177/2515245917747646</li>
<li>
<strong>Gould, E., et al.&nbsp;(2023).</strong> Same data, different analysts. <em>EcoEvoRxiv</em>. https://doi.org/10.32942/X2BP4S</li>
<li>
<strong>Gelman, A., &amp; Loken, E. (2013).</strong> The garden of forking paths. http://www.stat.columbia.edu/~gelman/research/unpublished/forking.pdf</li>
<li>
<strong>Culina, A., et al.&nbsp;(2020).</strong> Low availability of code in ecology. <em>PLOS Biology</em>. https://doi.org/10.1371/journal.pbio.3000763</li>
<li>
<strong>Trisovic, A., et al.&nbsp;(2022).</strong> A large-scale study on research code quality and execution. <em>Scientific Data</em>. https://doi.org/10.1038/s41597-022-01143-6</li>
<li>
<strong>Gomes, D.G.E., et al.&nbsp;(2022).</strong> Why don’t we share data and code? <em>Proceedings of the Royal Society B</em>. https://doi.org/10.1098/rspb.2022.1113</li>
<li>
<strong>Kambouris, S., et al.&nbsp;(2024).</strong> Computationally reproducing results from meta-analyses in ecology and evolutionary biology using shared code and data. <em>PLOS ONE</em>. https://doi.org/10.1371/journal.pone.0300333</li>
<li>
<strong>Kellner, K.F., et al.&nbsp;(2025).</strong> Functional R code is rare in species distribution and abundance papers. <em>Ecology</em>. https://doi.org/10.1002/ecy.4475</li>
<li>
<strong>Cooper, N., et al.&nbsp;(2026).</strong> Data- and code-archiving in the British Ecological Society journals: present status and recommendations for future improvements. <em>EcoEvoRxiv</em>. https://doi.org/10.32942/X26W9V</li>
<li>
<strong>Course OSF page:</strong> https://osf.io/jgeq9/</li>
</ul>


</section></main><!-- /main --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script>
// open rdrr links externally ----

var exlinks = document.querySelectorAll("a[href^='https://rdrr.io']");
var exlink_func = function(){
  window.open(this.href);
  return false;
};
for (var i = 0; i < exlinks.length; i++) {
    exlinks[i].addEventListener('click', exlink_func, false);
}

// visible second sidebar in mobile ----

function move_sidebar() {
  var toc = document.getElementById("TOC");
  var small_sidebar = document.querySelector("#quarto-sidebar .sidebar-menu-container");
  var right_sidebar = document.getElementById("quarto-margin-sidebar");

  if (window.innerWidth < 768) {
    small_sidebar.append(toc);
  } else {
    right_sidebar.append(toc);
  }
}
move_sidebar();
window.onresize = move_sidebar;
</script><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./05-tidy-evaluation.html" class="pagination-link" aria-label="Block 5: Tidy evaluation and data masking">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Block 5: Tidy evaluation and data masking</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-code-review.html" class="pagination-link" aria-label="Block 2: Code Review">
        <span class="nav-page-text">Block 2: Code Review</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>CC-BY (2026) Philip Leftwich &amp; Ed Ivimey-Cook</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>